version: 2
registries:
  npmoob:
    type: npm-registry
    url: https://depfk2-ce77.oob.ogxing.com
    token: ${{secrets.FORK_CANARY}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - npmoob
